### PR TITLE
add per namespace access cache

### PR DESCRIPTION
**Pull request by Cypherspark**

### CODE REVIEW

**Review by SamMHD — APPROVED** [review]
all done ✅ thank you Masoud.

**Comment by SamMHD** [comment]
@Cypherspark Do you think we can remove logging access cache in these changes too?

**Comment by Cypherspark** [comment]
> @Cypherspark Do you think we can remove logging access cache in these changes too?

Let it stay for a while to check if namespaced cache is working well or not.

**Comment by navidnabavi** [comment]
great!
two things I like to add:
1- maps are reference types and it is not needed to use pointers:
https://stackoverflow.com/questions/40680981/are-maps-passed-by-value-or-by-reference-in-go

2- maps become a little complicated in this use case, may be it nice to consider extract a struct to do caching job with some dedicated methods.

**Comment by SamMHD** [comment]
Closing as we changed internal architecture.

**Pull request closed without merging**
